### ISSUE TITLE
Research JavaScript physics engines

### ISSUE THREAD

**Issue by brylie** [OpenLearningQuest/experiments#2]
We want to create some simple experiments using physics, such as gravity, momentum, and buoyancy. While we may end up writing completely custom code, using an existing physics engine may save some time up front.

## Task

- [ ] create a list of existing physics engines that can run in a web browser
- [ ] create a comparison document describing the differences and similarities among the findings
- [ ] save a list of references, such as other comparison tables or how-tos
